name = "switchquote"
main = ".open-next/worker.js"
compatibility_date = "2025-01-15"
compatibility_flags = ["nodejs_compat", "global_fetch_strictly_public"]

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[[services]]
binding = "WORKER_SELF_REFERENCE"
service = "switchquote"

[[d1_databases]]
binding = "DB"
database_name = "switchquote"
database_id = "3cef716a-f944-410f-a3f6-f71f8fb662b2"
migrations_dir = "migrations"

[images]
binding = "IMAGES"
